server:
  port: 8084
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
app:
  file:
    storage-dir: D:/upload
    download-prefix: http://localhost:8888/savorgo/api/file/media/download/
aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  bucketName: ${AWS_BUCKET_NAME}
  rekognition:
    # Ngưỡng độ tin cậy (0-100). Mặc định 80%
    confidence-threshold: 80.0

logging:
  level:
    software.amazon.awssdk: DEBUG
    iuh.fit.fe.service: DEBUG
